title: Monkey Brain
description: A Brain for evolution!
theme: just-the-docs

url: https://owenducklee.github.io/MonkeyBrain/

aux_links:
  Monkey Brain Repository: https://github.com/OwenDuckLee/MonkeyBrain/tree/main
